language: python
dist: xenial
sudo: true

python:
  - "3.6"

services:
  - postgresql

addons:
  postgresql: "11"
  apt:
    packages:
      - postgresql-11
      - postgresql-client-11

env:
  global:
    - SECRET_KEY=vah6raGhah5Tee2Ejai5eiT2ealooj5vae4aiJu6
    - DB_HOST=localhost
    - DB_PASSWORD=''


install:
  - pip install -e .[dev]

script:
  - pytest -v --cov
  - pycodestyle feedsubs reader um

after_success:
  - pip install python-coveralls
  - coveralls

notifications:
    email: false
